definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  description: This is server for Archivit API.
  title: ARCHIVIT API
  version: latest
paths:
  /auth/google/login:
    get:
      consumes:
      - application/json
      description: google login handler
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: google login handler
  /auth/login:
    post:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User created successfully
          schema:
            type: string
        "400":
          description: Invalid user data
          schema:
            type: string
      summary: login user
  /auth/signup:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User created successfully
          schema:
            type: string
        "400":
          description: Invalid user data
          schema:
            type: string
      summary: register user
  /file/delete:
    delete:
      consumes:
      - multipart/form-data
      description: delete file
      parameters:
      - description: file txt and m4a
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: File deleted successfully
          schema:
            type: string
        "400":
          description: Invalid JWT
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: delete file
  /ping:
    get:
      consumes:
      - application/json
      description: do ping hello
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: ping example
  /record/create:
    post:
      consumes:
      - multipart/form-data
      description: create record
      parameters:
      - description: file m4a
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Record created successfully
          schema:
            type: string
        "400":
          description: Invalid JWT
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: create record
  /text/create:
    post:
      consumes:
      - multipart/form-data
      description: create file
      parameters:
      - description: file txt
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: File created successfully
          schema:
            type: string
        "400":
          description: Invalid JWT
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: create file
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
